version: "3.7"

services:
  # ----------------- UI Consumer --------------------
  ui-consumer:
    image: open-data-service/ods-main/ui-consumer
    build:
      context: ./ui
      dockerfile: Dockerfile.consumer
    volumes:
      - ./pacts:/app/pacts

  # ----------------- NOTIFICATION Consumer --------------------
  notification-consumer:
    image: open-data-service/ods-main/notification-consumer
    build:
      context: ./notification
      dockerfile: Dockerfile.consumer
    volumes:
      - ./pacts:/app/pacts